services:
  db:
    image: parjom/timescaledb-postgis:latest-pg16-postgis350
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:8000"
  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    command: celery -A celery_app.celery_app worker --loglevel=info --concurrency=2

volumes:
  db_data:
