version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: trips-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: trips-api
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "${API_PORT}:8000"

volumes:
  db_data:
